name: cns_ml
channels:
  - conda-forge
  - bioconda
dependencies:
  - r-base
  - r-tidyverse
  - r-survival
  - r-survminer
  - r-gtsummary
  - r-caret
  - r-glmnet
  - r-kernlab
  - r-xgboost
  - r-plyr
  - r-cowplot
  - r-pheatmap
  - r-factoextra
  - r-reshape2
  - r-rcolorbrewer
  - r-complexheatmap
  - r-clustree
  - r-ggpubr
  - r-data.table
  - r-readxl
  - r-openxlsx
  - r-yaml
  - r-usefun
  - r-rmarkdown
  - r-knitr
  - pandoc
  - bioconductor-minfi
  - bioconductor-illuminahumanmethylation450kanno.ilmn12.hg19
  - bioconductor-curatedtcgadata
  - bioconductor-tcgautils
  - bioconductor-multiassayexperiment
  - bioconductor-tcgabiolinks
  - bioconductor-keggrest
  - bioconductor-org.hs.eg.db
  - r-rpmm
  - python
  - pip
  - pip:
      - flexynesis
      - torch
      - numpy
      - pandas
      - scipy
      - scikit-learn
      - matplotlib
      - seaborn
      - requests
      - lifelines
